CHANGELOG.md, package.json, pnpm-lock.yaml, src/extension.ts, src/helpers/config.ts, src/helpers/configWatcher.ts, src/ux/HttpApiConnection.ts, src/ux/index.ts, src/ux/radCliInstallation.ts, src/ux/radicleIdentityAuth.ts
=> feat(config): make radicle HTTP API endpoint configurable

CHANGELOG.md, package.json, src/helpers/command.ts, src/utils/exec.ts, src/utils/git.ts, src/ux/HttpApiConnection.ts, src/ux/index.ts, src/ux/radicleProject.ts
=> feat(commands): add vscode cmd to clone a tracked radicle project

.github/workflows/ci.yaml, CHANGELOG.md, package.json, pnpm-lock.yaml
=> chore(build): support runtime deps by bundling with esbuild

README.md
=> docs(readme): add missing emoji for onboarding flow highlight

CHANGELOG.md, src/helpers/radCli.ts, src/ux/radicleIdentityAuth.ts
=> refactor(cli): use new options instead of regex when calling `rad self`

.eslintrc.js, .vscode/settings.json, CHANGELOG.md, package.json, pnpm-lock.yaml, src/helpers/config.ts, src/helpers/radCli.ts, src/utils/exec.ts, src/ux/radCliInstallation.ts, src/ux/radicleIdentityAuth.ts, tsconfig.json
e.g. dependency upgrades, fix offending source code to comply with upgraded linter, etc...
=> chore(repo): carry-out misc maintenance tasks

.vscode/settings.json, CHANGELOG.md, src/helpers/radCli.ts
=> fix(cli): migrate to new flag used to get RID

CHANGELOG.md, src/types/httpd.ts, src/utils/string.ts, src/webviews/src/components/Reactions.vue
=> feat(patch-detail): improve how reactions are shown

CHANGELOG.md, package.json
=> chore(scripts): parallelize verifying extension and webview dependencies

.github/workflows/ci.yaml, .github/workflows/commit-linting.yaml, .github/workflows/pr-linting.yaml, CHANGELOG.md
=> ci: speculative fix for flaky dep installs

CHANGELOG.md, src/webviews/src/components/PatchDetailActivity.vue, src/webviews/src/components/PatchDetailRevision.vue
=> fix(patch-detail): show the correct review author

CHANGELOG.md, package.json, src/stores/patchStore.ts, src/types/httpd.ts, src/ux/patchesView.ts
=> feat(patch-list): improve UX and perf

CHANGELOG.md, CONTRIBUTING.md, README.md, package.json
=> docs: update links to point to radicle

CHANGELOG.md, src/types/httpd.ts, src/ux/patchesView.ts
=> fix(patch-list): don't throw error when expanding patch item

CHANGELOG.md, CONTRIBUTING.md, README.md
=> docs(contributing): add new sections referencing zulip, issues, cloning

CHANGELOG.md, CONTRIBUTING.md, src/env.d.ts, src/helpers/webview.ts, src/stores/envStore.ts, src/stores/index.ts, src/types/webviewInjectedState.ts, src/utils/time.ts, src/webviews/src/components/EventItem.vue, src/webviews/src/components/PatchDetailRevision.vue, src/webviews/src/components/PatchMajorEvents.vue, src/webviews/src/stores/patchDetailStore.ts
=> feat(patch-detail): show localized dates

CHANGELOG.md, src/helpers/command.ts, src/ux/radicleIdentityAuth.ts, src/ux/repo.ts
=> feat(commands): show a busy indicator for long-running tasks

CHANGELOG.md, package.json, pnpm-lock.yaml
=> chore(deps): decrease minimum required vscode version

CHANGELOG.md, package.json, src/webviews/package.json
Signed-off-by: Konstantinos Maninakis <maninak@protonmail.com>
=> chore(dev): don't require approval for npx; use latest pnpm in scripts

CHANGELOG.md, src/stores/gitStore.ts, src/stores/patchStore.ts, src/utils/git.ts, src/ux/checkOut.ts
=> feat(commands): check the upstream branch for patch checkout status

CHANGELOG.md, package.json
=> fix(commands): replace "project" --> "repository" in cmd title

CHANGELOG.md, src/webviews/src/components/Markdown.vue
=> feat(style): polish and homogenize styles of (un-)ordered/task lists

CHANGELOG.md, src/webviews/src/components/Markdown.vue, src/webviews/src/components/PatchDetail.vue, src/webviews/src/components/PatchDetailActivity.vue, src/webviews/src/components/PatchDetailButtons.vue, src/webviews/src/components/PatchDetailRevision.vue, src/webviews/src/components/PatchMetadata.vue
=> fix(patch-detail): copy improvements

CHANGELOG.md, src/helpers/fetchFromHttpd.ts, src/stores/patchStore.ts, src/types/httpd.ts
=> fix(patch-list): show all patches, not only "open" ones

CHANGELOG.md, package.json, src/helpers/command.ts, src/helpers/webview.ts, src/ux/patchesView.ts, src/webviews/src/components/PatchDetailButtons.vue
=> feat(patch-list): improve patch context menu commands

CHANGELOG.md, src/webviews/src/components/PatchDetailRevision.vue
=> feat(patch-detail): add buttons to copy revision's commit SHAs

CHANGELOG.md, src/ux/checkOut.ts
=> feat(commands): better detect why check-out failed and offer go-to-scm

CHANGELOG.md, README.md, src/helpers/fetchFromHttpd.ts, src/stores/patchStore.ts, src/types/httpd.ts, src/ux/patchesView.ts, src/ux/repo.ts
=> fix(httpd): support v0.17.0

.eslintrc.js, package.json, pnpm-lock.yaml
Closes no specific issue.
Complements #35
=> chore(lint): require blank line before expect statements, etc
